### ISSUE TITLE
Potential typo in Definition 7 (Multilevel quality)

### ISSUE THREAD

**Issue by wilfreddenton** [dionyziz/popow#56]
<img width="883" alt="screen shot 2018-01-22 at 10 42 46 pm" src="https://user-images.githubusercontent.com/1426935/35291719-3201d490-003c-11e8-9f9d-fd40cdd03812.png">

I believe that it should be `2^(μ'-μ)` not `2^(μ-μ')`.

`|C*↑μ|` is strictly less than `|C*↑μ'|` where `μ' < μ`. This is because lower levels contain more blocks: `1/2` of all blocks are of `μ=1`, `1/4` of all blocks are of `μ=2`, etc. So, for this inequality to be true, the quantity multiplied by `|C*↑μ'|` should be `< 1`. However, `μ-μ' >= 1` making `2^(μ-μ') >= 2` so `(1-δ)2^(μ-μ') >= 1` for all `δ <= 0.5`.

My apologies if I have overlooked something.

**Comment by dionyziz** [comment]
Thanks for pointing out the error. You're right. I have incorporated the change in the latest version in preparation for an eprint update.

**Comment by dionyziz** [comment]
[Fixed here](https://github.com/dionyziz/popow/commit/7b27f59bf09f2d02fa49ae4d0d46a52a2a841031)
